# remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
# plugins: 
# - jekyll-remote-theme
title: Renewable Bermagui
description: Community-led energy change on the NSW Far South Coast
author: alex
timezone: Australia/Melbourne

logo: "/assets/logos/RB_logo_landscape.png" # Site logo, also used in jekyll-seo-tag

navigation_header:
- title: Get in Touch
  url: /#get-in-touch
- title: Archive
  url: /archive
- title: Resources
  url: /resources


navigation_footer:
- title: Renewable Bermagui
  url: https://renewablebermagui.github.io


social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Instagram: https://instagram.com/renewable_bermagui
  Facebook: https://facebook.com/renewablebermagui
  Email: mailto:hello@renewablebermagui.org
  
bermi_socials:
- name: Facebook
  id: facebook
  link: https://facebook.com/renewablebermagui
  colour: "#0366d6"
- name: Instagram
  id: instagram
  link: https://instagram.com/renewable_bermagui
  colour: "#cf11ffff"
- name: Email
  id: email
  link: mailto:hello@renewablebermagui.org
  colour: "#499403ff"


defaults:
  -
    scope:
      path: ""
    values:
      feature_image: "/img/gulaga_2000_900.jpg"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages


fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap
    - https://fonts.googleapis.com/css2?family=Bitcount+Prop+Single:wght@100..900&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap

favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
   16: '/img/favicon/rb-favicon-16x16.png'
   32: '/img/favicon/rb-favicon-32x32.png'
#   96: '/assets/logos/logo@96px.png'
#   120: '/assets/logos/logo@120px.png'
#   144: '/assets/logos/logo@144px.png'
   192: '/img/favicon/rb-favicon-192x192.png'
   512: '/img/favicon/rb-favicon-512x512.png'
#   1024: '/assets/logos/logo@1024px.png'
